services:
  - type: web
    name: bicicletario-online
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: DATABASE_URL
        fromDatabase:
          name: bicicletario-db
          property: connectionString

databases:
  - name: bicicletario-db
    databaseName: bicicletario
    user: bicicletario
    plan: free
